# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI pipeline with K6 integrated

on:
  push:

jobs:
  k6_local_test:
    name: k6 local test on macos
    runs-on: macos-latest
  
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install k6 by homebrew
      run: brew install k6

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: build
      run: yarn start --silent &
        
    - name: Local k6 test
      with: # Set the secret as an input
        LOAD_IMPACT_TOKEN: ${{ secrets.LoadImpactToken }}
        run: k6 login cloud -t "$LOAD_IMPACT_TOKEN"
      name: Run the test
      run: yarn test



